version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfacon-forum-app
    restart: always
    command: 'yarn dev'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file: .env

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  node_modules: